### ISSUE TITLE
Connection Maiar Echange-Maiar App not working

### ISSUE THREAD

**Issue by Crilocambiodopo** [multiversx/mx-battleofyields-site#1075]
erd1gm0l905eyrplq95feqg3qys5hjt4v9vzmhjh4zjetnhg7wau8u2qdva3u4

Since two days, very often I cannot do transactions, because it is impossible to sign the authorization, given that they simply don't appear into the Maiar app. 

Even when I log out and reconnect it doesn't always work. I don't know if I am an isolated case, because I have asked about this situation into the BOY group chat and nobody confirmed. However, from a user experience perspective, for me it is quite frustrating.

**Comment by hanahdev** [comment]
> erd1gm0l905eyrplq95feqg3qys5hjt4v9vzmhjh4zjetnhg7wau8u2qdva3u4
> 
> Since two days, very often I cannot do transactions, because it is impossible to sign the authorization, given that they simply don't appear into the Maiar app.
> 
> Even when I log out and reconnect it doesn't always work. I don't know if I am an isolated case, because I have asked about this situation into the BOY group chat and nobody confirmed. However, from a user experience perspective, for me it is quite frustrating.

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
