### ISSUE TITLE
Idea for the exchange  

### ISSUE THREAD

**Issue by BogdanBoros93** [multiversx/mx-battleofyields-site#1076]
I know this is where to post issues, but i do not know where to post an ideea for the exchange 😅. So, my idea is that when withdrawing from the farm or removing liquidity there should be something showing you the value in dolars of the percentage that you want to withdraw /remove, because, sometimes, i do not want to withdraw /remove all of it, but just a bit.
![Screenshot_20210925_101315_com whatsapp](https://user-images.githubusercontent.com/90897453/134762542-aa21f93c-d0ee-44e4-afeb-3ace648ed90c.jpg)

**Comment by Broscuta** [comment]
Yes! I agree!
