### ISSUE TITLE
erd133v8vmvjzcagxdtrfvdtydqda35sl5ucs55h83v5gz5s47xwk4dq58m0x6

### ISSUE THREAD

**Issue by amateen42** [multiversx/mx-battleofyields-site#1103]
I'm unable to harvest any rewards, apr/apy shows 0/0, the farm page only shows LP tokens but not rewards, it's been like this for half an hour now

**Comment by Broscuta** [comment]
Mex rewards are stoped between 9:00 UTC and 13:00 UTC

https://t.me/MaiarExchange
Read the pined messages!
