### ISSUE TITLE
Maiar app login

### ISSUE THREAD

**Issue by Peccious** [multiversx/mx-battleofyields-site#1166]
Almost each time I login with Maiar app '' Maiar login error'' message appears. And when I manage to login after confirmation of transaction my Maiar login expires and I get again' 'Maiar login error''. I updated Maiar app and same error continues.
I am using Huawei P20 pro CLT-L29, Android 10, Chrome newest version. 

erd14kujelh4ewpp80a8ljp2mwkx2edj7mpej5hnnrfxnrjx8pg0l9gq8zav6d

![Screenshot_20210928_135903_com android chrome](https://user-images.githubusercontent.com/91560114/135134904-45ddce23-9e24-46ad-ab77-1468327c35d7.jpg)
![Screenshot_20210928_140107_com android chrome](https://user-images.githubusercontent.com/91560114/135134906-3f309b9f-0ea6-4c90-95b6-63890efdc9ff.jpg)
![Screenshot_20210928_135908_com android chrome](https://user-images.githubusercontent.com/91560114/135134907-35ea55ba-a309-4580-b02b-cc6e94020cfc.jpg)
![Screenshot_20210928_140152_com android chrome](https://user-images.githubusercontent.com/91560114/135134912-b86d5163-31c8-45ab-94e6-e247fc074e43.jpg)

**Comment by hanahdev** [comment]
> Almost each time I login with Maiar app '' Maiar login error'' message appears. And when I manage to login after confirmation of transaction my Maiar login expires and I get again' 'Maiar login error''. I updated Maiar app and same error continues. I am using Huawei P20 pro CLT-L29, Android 10, Chrome newest version.
> 
> erd14kujelh4ewpp80a8ljp2mwkx2edj7mpej5hnnrfxnrjx8pg0l9gq8zav6d
> 
> ![Screenshot_20210928_135903_com android chrome](https://user-images.githubusercontent.com/91560114/135134904-45ddce23-9e24-46ad-ab77-1468327c35d7.jpg) ![Screenshot_20210928_140107_com android chrome](https://user-images.githubusercontent.com/91560114/135134906-3f309b9f-0ea6-4c90-95b6-63890efdc9ff.jpg) ![Screenshot_20210928_135908_com android chrome](https://user-images.githubusercontent.com/91560114/135134907-35ea55ba-a309-4580-b02b-cc6e94020cfc.jpg) ![Screenshot_20210928_140152_com android chrome](https://user-images.githubusercontent.com/91560114/135134912-b86d5163-31c8-45ab-94e6-e247fc074e43.jpg)

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281

**Comment by Peccious** [comment]
Hi, thanx for your answer, but issue has been resolved.

     Enjoy!!!!
