### ISSUE TITLE
Maiar app disconnect

### ISSUE THREAD

**Issue by BogdanBoros93** [multiversx/mx-battleofyields-site#1190]
Once again, on my android phone (Huawei P30 PRO) the Maiar app keeps disconnecting after a short period of time of running in the background.

**Comment by hanahdev** [comment]
> Once again, on my android phone (Huawei P30 PRO) the Maiar app keeps disconnecting after a short period of time of running in the background.

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
