### ISSUE TITLE
erd1tp5rsjlkhww8zkpzpmykc3l9s6s4z7pp92ysx7kxrde6fml9kryqwsy57c not showing balance on farm

### ISSUE THREAD

**Issue by DN29** [multiversx/mx-battleofyields-site#249]
my liquidity is in EGLD/BUSD
![image](https://user-images.githubusercontent.com/90720660/133317761-7d745bd6-0284-4f02-903d-e803335db7f8.png)

but not displaying on the farm page EGLD/BUSD
![image](https://user-images.githubusercontent.com/90720660/133317688-972527d5-c46e-4ecf-88e5-917385bf51f5.png)

**Comment by astrolyf** [comment]
I believe once you add the liquidity, you have to stake it in the respective farm. In this case, you have to press stake on the EGLD-BUSD farm and select your EGLD-BUSD pair to stake.

**Comment by DN29** [comment]
right just notice thanks

**Comment by DN29** [comment]
but should it just be automatic like Kava app? more simple much better than pancakes wap

**Comment by DN29** [comment]
As I can tell they didnt have an approve function to staked these tokens.

**Comment by rxdhwan** [comment]
Probably that could be the reason why it's a two-step process, the first step converts your liquidity into SFT which you can send and receive and the second step is staking the liquidity token into a farm. You earn from providing liquidity as well as farming APY.
