### ISSUE TITLE
reclaiming liquidity funds not working

### ISSUE THREAD

**Issue by ravenx29** [multiversx/mx-battleofyields-site#270]
andding liquidity failed,
reclaiming liquidity funds not working
https://testnet-explorer.elrond.com/transactions/c1a719074ba754573732ebd226937315df20f442255a26758a4d8e8834c53f98

**Comment by rxdhwan** [comment]
Provide more details such as your device, browser, etc. so that the team could look further into it.

**Comment by ravenx29** [comment]
Windows 10 pro, Google Chrome with Maiar DeFi extension
