### ISSUE TITLE
erd1z5npr3n9layu3uv2yvdyc8uaew2tk4mfgq30yky920ra0976n0eswktwwh

### ISSUE THREAD

**Issue by Madelaed** [multiversx/mx-battleofyields-site#364]
Issue name:

"Maiar app standby problem with exchange"

Issue description:

**### English :**

When you want to connect via maiar app to the exchange, it works. But if the phone goes to sleep or we reduce the maiar application on the phone, it disconnects us from maiar app but we remain connected to the exchange. But when we have to validate a transaction via maiar app, if the phone has gone to sleep or we have reduced maiar app, then it is impossible to validate the transaction.
You must then disconnect from maiar exchange and reconnect

**### **French :****

Quand on veut ce connecter via maiar app a l'exchange, ça fonctionne. Mais si le téléphone ce met en veille ou on réduit l'application maiar sur le téléphone, cela nous déconnecte de maiar app mais nous restons connecter a l'exchange. Mais lorsque que l'on doit validé une transaction via maiar app, si le téléphone s'est mit en veille ou que l'on a reduit maiar app, alors il est impossible de validé la transaction.
Il faut alors ce déconnecter de maiar exchange et ce reconnecter

**Comment by hanahdev** [comment]
> Issue name:
> 
> "Maiar app standby problem with exchange"
> 
> Issue description:
> 
> **### English :**
> 
> When you want to connect via maiar app to the exchange, it works. But if the phone goes to sleep or we reduce the maiar application on the phone, it disconnects us from maiar app but we remain connected to the exchange. But when we have to validate a transaction via maiar app, if the phone has gone to sleep or we have reduced maiar app, then it is impossible to validate the transaction. You must then disconnect from maiar exchange and reconnect
> 
> **### **French :****
> 
> Quand on veut ce connecter via maiar app a l'exchange, ça fonctionne. Mais si le téléphone ce met en veille ou on réduit l'application maiar sur le téléphone, cela nous déconnecte de maiar app mais nous restons connecter a l'exchange. Mais lorsque que l'on doit validé une transaction via maiar app, si le téléphone s'est mit en veille ou que l'on a reduit maiar app, alors il est impossible de validé la transaction. Il faut alors ce déconnecter de maiar exchange et ce reconnecter

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
