### ISSUE TITLE
Maiar

### ISSUE THREAD

**Issue by Laiarg** [multiversx/mx-battleofyields-site#367]
Maiar disconnect all time

erd17ge7d3jpvwfq7eshr4lnjq7pmrtwpnetlu4s8azdhlf467sz38tsxz0a55

**Comment by hanahdev** [comment]
> Maiar disconnect all time
> 
> erd17ge7d3jpvwfq7eshr4lnjq7pmrtwpnetlu4s8azdhlf467sz38tsxz0a55

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
