### ISSUE TITLE
erd17nzaj5dw79hsuutlxt3q5p93c6pd2dzp9845cahj3zq6uz5a9m9scjqyrx

### ISSUE THREAD

**Issue by alexbrunet1** [multiversx/mx-battleofyields-site#445]
Hi,
i register yesterday for the BOY and it was a bug i couldnt be registered
here is my elrond address and herotag:
erd17nzaj5dw79hsuutlxt3q5p93c6pd2dzp9845cahj3zq6uz5a9m9scjqyrx / alexbrunet

and here you can find me on telegram : tburn119

can you please do something and fix this 
thanks so much

**Comment by WebDices** [comment]
At what hour did you try to register? Was the "Join Now" button disabled? 

If so, the date for register was expired. I don't think you can do something regarding this.
