### ISSUE TITLE
[BUG] address has funds but EGLD is not visible in account details when connected to exchange

### ISSUE THREAD

**Issue by gsbat** [multiversx/mx-battleofyields-site#454]
Hi, 

No xEGLD showed up in my test account 
I received 2,500 BUSD
But can not claim MEX or make transactions

Although if I open account details on Elrond explorer it shows a balance of 5XeGLD

I am using an apple iPad as I do not have access to a desktop computer 

My wallet address is: erd160dyfyst978gjs2kq3xdxq0d7juheyqmgygp4xquwh7y8a5z5fshm6c28

Thanks,

Grace.

**Comment by gsbat** [comment]
Hi I still have no access to any xEGLD and can therefore can not start the battle of the yields 

https://linksharing.samsungcloud.com/jaOu03keLXkl
https://linksharing.samsungcloud.com/byLblutpk9hy

**Comment by frankf1957** [comment]
I confirmed the testnet wallet balance is as follows: 5.1000 xEGLD, 2500.000 BUSD.  There are no NFTs listed.

As such, this individual cannot participate in the Battle of Yields event.

**Comment by frankf1957** [comment]
This address seems to be affected by the same issue.  Assets can be seen in the testnet explorer but not in the Account Details page of the Exchange.

erd1f8lreflft8cwvhdg9mu3nsge4mc08p2t48529ttq9nrcw99kez5s6yrv5s

Reported at this link https://t.me/MaiarExchange/28993

**Comment by Sedimir** [comment]
Same issue as above.
User reported the issue here:
https://t.me/MaiarExchange/29759

I took it to DM, his address:
erd1lwmx0p7uk0lrp63dg60q8vtwyp64fdxk5y9htnvvjlags38dk6lq7avmqy

His configuration was iOS only, Maiar + Safari/Chrome.
Eventually restart of the device solved this for him...
