### ISSUE TITLE
Devnet Simple SEND Txn Pending For A Long Time

### ISSUE THREAD

**Issue by euphorical** [multiversx/mx-battleofyields-site#603]
So was playing around with tokens, sending, swapping, liquidity, etc. I tried sending devnet tokens from 1 account to another, but it's still pending... Very odd.

Txn Hash: 9d75d1fa3418a6f726d324f4ab5c8ed2d3aec2cc6d593858b74f49ed387a00e6

https://devnet-explorer.elrond.com/transactions/9d75d1fa3418a6f726d324f4ab5c8ed2d3aec2cc6d593858b74f49ed387a00e6

![screencapture-devnet-explorer-elrond-transactions-9d75d1fa3418a6f726d324f4ab5c8ed2d3aec2cc6d593858b74f49ed387a00e6-2021-09-16-17_47_31-edit](https://user-images.githubusercontent.com/5444311/133690286-155d2aa6-ae1c-4ff2-9d37-9598b1c9bfc3.png)

**Comment by Desmond5y** [comment]
Hi,
You have to be on: https://testnet.maiar.exchange/
