### ISSUE TITLE
Disconnected from Maiar app erd16797sws5y93rcc48qfn4zm83thk5asjpee4shwc5uvmrr3cv4xzsttl4sp

### ISSUE THREAD

**Issue by MarcBarbu** [multiversx/mx-battleofyields-site#722]
So, i am on iPhone, usong Chrome browser and my Maiar app to log in. 
I have noticed that the testnet and Maiar unlink very easy. Every single time i have a tranzaction issue, unfinished farm stake, or a staking issue or a swap issue or missing funds issue, or one of the 2/3/4 transactions i sign is not completed therefore canceling the whole thing, for everyone on those I found the dex and Maiar not linked. And they actually stay connected 10-15 seconds or so, therefore I get everyday all those errors (I have loads of print screens if needed).
Other other weird thing was a complete "blue screen" only in white. ![image](https://user-images.githubusercontent.com/90727064/133882849-a0cd4453-e1a1-45cb-ba60-6d40426d92bc.png)

**Comment by hanahdev** [comment]
> So, i am on iPhone, usong Chrome browser and my Maiar app to log in. I have noticed that the testnet and Maiar unlink very easy. Every single time i have a tranzaction issue, unfinished farm stake, or a staking issue or a swap issue or missing funds issue, or one of the 2/3/4 transactions i sign is not completed therefore canceling the whole thing, for everyone on those I found the dex and Maiar not linked. And they actually stay connected 10-15 seconds or so, therefore I get everyday all those errors (I have loads of print screens if needed). Other other weird thing was a complete "blue screen" only in white. ![image](https://user-images.githubusercontent.com/90727064/133882849-a0cd4453-e1a1-45cb-ba60-6d40426d92bc.png)

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
