### ISSUE TITLE
O have a bug.

### ISSUE THREAD

**Issue by Mikigold7** [multiversx/mx-battleofyields-site#748]
the account on Maiar dex stays connected to me and the one on Maiar app disconnected. I always have this problem when 
![Screenshot_20210918-195534_Maiar](https://user-images.githubusercontent.com/90877106/133896627-8b4afc9f-b7f8-4df2-91e9-557e12e8ce19.jpg)
![Screenshot_20210918-195540_Samsung Internet](https://user-images.githubusercontent.com/90877106/133896628-cbe1f212-d1ee-426e-8745-363922ca04fb.jpg)

**Comment by hanahdev** [comment]
> the account on Maiar dex stays connected to me and the one on Maiar app disconnected. I always have this problem when ![Screenshot_20210918-195534_Maiar](https://user-images.githubusercontent.com/90877106/133896627-8b4afc9f-b7f8-4df2-91e9-557e12e8ce19.jpg) ![Screenshot_20210918-195540_Samsung Internet](https://user-images.githubusercontent.com/90877106/133896628-cbe1f212-d1ee-426e-8745-363922ca04fb.jpg)

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
