### ISSUE TITLE
Multiple claim transactions waiting

### ISSUE THREAD

**Issue by necsoiu** [multiversx/mx-battleofyields-site#783]
![Capture](https://user-images.githubusercontent.com/1866443/133928815-f2a257a6-402a-41e1-8298-70a835d41214.PNG)

**Comment by soringp** [comment]
Same for me when claiming on the Shard 1 wallet:

erd1dktfdn6pw5k4zlymr4r67netrvdfmd6zk60rqfvtrxdp3gzf438s3rdtgu

![image](https://user-images.githubusercontent.com/16723548/133929366-7b605bbc-3ae8-4553-b64f-adae6555ad8c.png)
