### ISSUE TITLE
Maiar app

### ISSUE THREAD

**Issue by Jpjz** [multiversx/mx-battleofyields-site#856]
Hi.   Doing the BoY and performing transactions, when I open the maiar app, it has the number 6, noting I have 6 messages or notifications but when I open the app, I can’t see where to open these notifications so it just keeps the number 6 there.  Thanks

**Comment by hanahdev** [comment]
> Hi. Doing the BoY and performing transactions, when I open the maiar app, it has the number 6, noting I have 6 messages or notifications but when I open the app, I can’t see where to open these notifications so it just keeps the number 6 there. Thanks

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
