### ISSUE TITLE
Delayed signature transcation

### ISSUE THREAD

**Issue by cataovi** [multiversx/mx-battleofyields-site#94]
When i sign a transaction there is a delay. I sign the transaction in Maiar aplication and many times apears in maiar to sign 2-3 times same transaction that i have done on Maiar Dex platform.

**Comment by hanahdev** [comment]
> When i sign a transaction there is a delay. I sign the transaction in Maiar aplication and many times apears in maiar to sign 2-3 times same transaction that i have done on Maiar Dex platform.

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
