### ISSUE TITLE
Maiar notification

### ISSUE THREAD

**Issue by Sabin04** [multiversx/mx-battleofyields-site#949]
The notification says "Elrond Wallet" requests you to sign a transaction when it should say "Maiar Exchange" 

![image](https://user-images.githubusercontent.com/90719670/134184153-525c4b0b-270b-493e-a977-2f4ec2804108.png)

**Comment by hanahdev** [comment]
> The notification says "Elrond Wallet" requests you to sign a transaction when it should say "Maiar Exchange"
> 
> ![image](https://user-images.githubusercontent.com/90719670/134184153-525c4b0b-270b-493e-a977-2f4ec2804108.png)

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
