### ISSUE TITLE
wrong connection between exchange & maiar

### ISSUE THREAD

**Issue by BennyMarincu** [multiversx/mx-battleofyields-site#991]
I'm logged in in exchange and maiar as well. Exchange want confirmation through maiar. Nothing in maiar to sign. Ongoing processes in exchange never finalising on exchange startup

**Comment by hanahdev** [comment]
> I'm logged in in exchange and maiar as well. Exchange want confirmation through maiar. Nothing in maiar to sign. Ongoing processes in exchange never finalising on exchange startup

we are so sorry for the late reply kindly contact there live chat support on whatsapp -  +19546679281
